### PR TITLE
Firefox support too :)

### PR DESCRIPTION
**Pull request by kirsn**
Hello @agarden,
I liked your chrome extension, and I borrowed that idea to create a Firefox extension too.
As part of this, I went ahead and restructured the contents of the repository, and included the new files for the firefox addon.
I would like this code to reside in your repository, instead of my fork. Hope this works for you? 
Please let me know if you require any clarifications : subbaraman dot kiran at gmail.

Thank you,
Kiran

### CODE REVIEW

**Comment by agarden** [comment]
Hey, that's great! So with your changes, this one package can be used in either Chrome or Firefox? I don't have time to test and find out for myself right now. I will look over your work in more detail when I can. Love the idea.

**Comment by kirsn** [comment]
No, I haven't created a common code base. Though, I think the `contentscript.js` can be shared between the firefox, and chrome extensions ( I need to try that out, and also probably get rid of the `live.js`).
What I have done is:
- create a folder containing the codebase for the firefox extension
- create a folder for the chrome extension codebase, and move your current code into that.
- rename the project to web2py-devmode-browser-extension ... since it contains both chrome, and firefox codebases. Alter the README to reflect these changes.
- create the .xpi file for firefox, and put that up in the release (https://github.com/kirsn/web2py-devmode-browser-extension/releases)
- once this code base is merged, then we can release the firefox and chrome extensions from here.

**Comment by kirsn** [comment]
I went back, and refactored the code a bit, so that I don't have redundant code. I will close this PR, and re-issue a new one.

**Comment by agarden** [comment]
I'm sorry. I was busy when you filed this pull request and wanted to look
over your code before merging it. And then my summer went horribly,
horribly wrong and I haven't kept on top of much of anything for the last
few months. Anyway, I am excited that this was useful enough to you that
you put the work in to port it to FireFox. Thanks. It's merged now.

**Comment by kirsn** [comment]
No problem at all. Am glad you were able to merge this.

**Pull request closed without merging**
